import sys, socket
buf = "pattern generated by pattern_create.rb"
try:
	s = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
	s.connect(('IP',PORT))
	s.send(('TRUN /.:/' + offset))
	s.close()
except:
	print("Error connecting to server")
	sys.exit()
